version: '3'

networks:
    streamlabs-net:
        driver: "bridge"

volumes:
    mysql-data:
    redis-data:

services:
    mysql:
        image: mysql:8.0
        container_name: streamlabs-mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - streamlabs-net

    redis:
        restart: always
        container_name: streamlabs-redis
        image: redis:latest
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        volumes:
            - redis-data:/data
        networks:
            - streamlabs-net

